In [1]:
from numpy import array, diag, diagflat, dot
from numpy.linalg import inv
import numpy as np

In [2]:
A = np.array([[8,1],[1,12]]) #matrix A
b = np.array([1,2]) # matrix b
x = np.array([0,0]) # initial guess value of [x]
epsi = 0.000001 #tolerance

In [3]:
U = np.triu(A,1)
L = np.tril(A,-1)
D = diagflat(diag(A))
inv_D = inv(D)
print('U = ')
print(U)
print('L = ')
print(L)
print('D = ')
print(D)

# A = L+D+U

U = 
[[0 1]
 [0 0]]
L = 
[[0 0]
 [1 0]]
D = 
[[ 8  0]
 [ 0 12]]


In [4]:
#x(k+1)=inv(D)[-Ux(k)+b]
for i in range(200):
    J = -(L+U)
    x = dot(dot(J,x)+b,inv_D)
    err = np.dot(A, x) - b
    if abs(np.mean(err))<epsi :
        break
    #print('for ',i,'iteration the solution is ',list(map('{:.7f}'.format,x)))

print('for ',i,'iteration the solution is ',x)

for  6 iteration the solution is  [0.10526318 0.15789475]
